In [1]:
import numpy as np

In [3]:
# matrix
x = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(x)
print(x)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# 2d matrix
y = [[[1,9,0],[2,5,6],[3,2,1]], [[4,7,8],[5,4,8],[6,5,4]],[[6,8,5],[6,8,7],[9,8,7]]]
y = np.array(y)
print(y)

[[[1 9 0]
  [2 5 6]
  [3 2 1]]

 [[4 7 8]
  [5 4 8]
  [6 5 4]]

 [[6 8 5]
  [6 8 7]
  [9 8 7]]]


In [11]:

# zeroes of matrix
z = np.zeros((3,3)) + 5
print(z)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [13]:
# ones of matrix
w = np.ones((4,4)) * 5
print(w)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [18]:
#identity matrix
u = np.eye((4)) 
print(u)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
u = np.eye((4)) * 5
print(u)

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [21]:
# creating array within a range
print(np.arange(10))
print(np.arange(4,10))

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]


In [22]:
#2d matrix using a range
print(np.arange(50).reshape(5,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [37]:
#linspaces creates equal linear spaces within the specified range
print(np.linspace(0,100,5))

[  0.  25.  50.  75. 100.]


In [41]:
print(np.random.rand(5))
print(np.random.randint(5,100, 9))

[0.99741065 0.19294185 0.1360216  0.17044991 0.07944951]
[58 70 60 94 59 18 76 45 87]


In [48]:
t = [1,2,3,4,5,6,7]
t = np.array(t)
print(t.max())
print(t.min())
#index of the max & min value
print(t.argmax())
print(t.argmin())

7
1
6
0


In [58]:
x = np.arange(0,20)

In [59]:
x[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x[2:5]

array([2, 3, 4])

In [64]:
y = x[5:15] = 40
print(y)
print(x)

40
[ 0  1  2  3  4 40 40 40 40 40 40 40 40 40 40 15 16 17 18 19]


In [70]:
y = x.copy()
y

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 15, 16,
       17, 18, 19])

In [73]:
y[5:15] =80
print(x)
print(y)

[ 0  1  2  3  4 40 40 40 40 40 40 40 40 40 40 15 16 17 18 19]
[ 0  1  2  3  4 80 80 80 80 80 80 80 80 80 80 15 16 17 18 19]


In [76]:
#Slicing
p = np.arange(25).reshape(5,5)
print(p)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [77]:
p[2][2]

12

In [80]:
p[0:2, 2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [82]:
print(p[2:,:3])

[[10 11 12]
 [15 16 17]
 [20 21 22]]


In [93]:
x = np.arange(0,20)

In [85]:
x > 12

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [95]:
x[x>12]

array([13, 14, 15, 16, 17, 18, 19])

In [96]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [94]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [97]:
s = np.arange(0,10)
r = np.arange(11,20)

In [98]:
np.sin(s)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [99]:
np.log(s)

C:\Users\HACADEMY\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [100]:
np.cos(s)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])